### ISSUE TITLE
Can't see the login page

### ISSUE THREAD

**Issue by phthhieu** [CSEugene/Airbrake_Clone#1]
When starting server and going to localhost:3000, I see this page:
<img width="1263" alt="screen shot 2016-07-08 at 10 49 36 am" src="https://cloud.githubusercontent.com/assets/3622010/16676882/d4d046e8-44f9-11e6-9b79-0614b86ac5eb.png">
But the expected UI would be:
<img width="1264" alt="screen shot 2016-07-08 at 10 51 29 am" src="https://cloud.githubusercontent.com/assets/3622010/16676901/faacb9b4-44f9-11e6-9eb4-8aeb3429f493.png">

Do I do anything wrong? Or this is the unfinished feature?

**Comment by CSEugene** [comment]
the login page is available at "localhost:3000/login" on my local machine. Did you add "/login" after that address?

**Comment by phthhieu** [comment]
Yes I see, it's wonderful, let me close this issue
